config/routes.rb
Sso::Application.routes.draw do
  get "secure/index"

  get "home/index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/sign_in" => "sessions#new", :as => :sign_in
  match "/sign_out" => "sessions#destroy", :as => :sign_out

  resources :identities

  root :to => "home#index"
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord

  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :uid, :provider, :name, :email

  def self.create_with_omniauth!(omni_data)
    create! do |user|
      user.uid = omni_data[:uid]
      user.provider = omni_data[:provider]
      user.name = omni_data[:info][:name]
      user.email = omni_data[:info][:email]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  protected

  def authenticate!
    redirect_to sign_in_url unless current_user 
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env["omniauth.identity"]
  end
end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
  before_filter :authenticate!

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def new
  end

  def create
   omniauth = request.env["omniauth.auth"] 
   user = User.find_by_uid_and_provider(omniauth[:uid].to_s, omniauth[:provider]) || User.create_with_omniauth!(omniauth)
   session[:user_id] = user.id

   redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/secure_helper.rb
module SecureHelper
end

app/views/home/index.html.erb
<h1>Unsecure page</h1>

<p>
  This is an unsecure page you can view it without being logged in.
</p>
<%= link_to "Secure page", secure_index_url %>

app/views/identities/new.html.erb
<h1>New Account</h1>

<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Register" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSO</title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Signed in as <%= current_user.name %>. Not you?
          <%= link_to "Sign out", sign_out_path %>
        <% else %>
          <%= link_to "Sign in", sign_in_path %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/secure/index.html.erb
<h1>Secure page</h1>

<p>
  This is a secure page.
  You should only see this if you have logged in successfully.
</p>

<%= link_to "Back to unsecure page", home_index_url %> 